Module2 task1
htmlacademy-react/2059779-six-cities-13 pull request #3
Opened 2023-07-07 08:28 UTC by PalantKellad

2023-07-07 10:52 UTC, baileys-li requested changes
Избавиться от key в компоненте обязательно, остальное по желанию

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +const WidthByRating: widthByRatingType = {
ок
```suggestion
const WidthByRating: Record<number, `${number}%` | `${number}`> = {
```

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +}
`key` не так работает
```suggestion
```

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +function OfferCard({ item }: offerCardPropType, { key }: keyPropType): JSX.Element {
Просто деструктуризация пропсов
```suggestion
function OfferCard({ item }: offerCardPropType): JSX.Element {
```

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +		<article key={key} className="cities__card place-card">
```suggestion
		<article className="cities__card place-card">
```

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +	const favoriteButtonClass = item.isFavorite ? 'place-card__bookmark-button place-card__bookmark-button--active button' : 'place-card__bookmark-button button';
У вас есть вспомогательный пакет для такого
```suggestion

	const favoriteButtonClass = classNames('place-card__bookmark-button', {
		'place-card__bookmark-button--active': item.isFavorite
	}, 'button');
```

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +			{item.isPremium ? <div className="place-card__mark"><span>Premium</span></div> : ''}
```suggestion
			{item.isPremium && <div className="place-card__mark"><span>Premium</span></div>}
```

2023-07-07 10:52 UTC, baileys-li commented on src/mocks/offers.ts
> +export interface IOffer {
Некогда не понимал привычку ставить какие-то буквы в начале

2023-07-07 10:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +	const starsCount = {
Уточним
```suggestion
	const starsCount: CSSProperties = {
```

2023-07-07 10:52 UTC, baileys-li commented on src/pages/main-page.tsx
> +								{offers.map((offer) => <OfferCard item={offer} key={crypto.randomUUID()} />)}
Лучше сразу взять схему из сваггера и в моках сгенерировать id 
```suggestion
								{offers.map((offer) => <OfferCard item={offer} key={offer.id} />)}
```

2023-07-07 10:52 UTC, baileys-li commented on src/mocks/offers.ts
> +		title: 'Beautiful & luxurious apartment at great location',
Попробуй поюзать faker.  Он уже есть у вас в зависимостях

2023-07-07 11:43 UTC, PalantKellad commented on src/components/offer-card/offer-card.tsx
> +	const starsCount = {
Правильно понимаю, что CSSProperties нужно сначала импортировать из Реакта?

2023-07-07 11:52 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +	const starsCount = {
Да

2023-07-08 09:23 UTC, baileys-li commented
@PalantKellad спуль свежий коммит

2023-07-09 15:27 UTC, merged