Module4 task1
htmlacademy-react/2059779-six-cities-13 pull request #5
Opened 2023-07-12 18:23 UTC by PalantKellad

Не получается пятый пункт задания:
«Добавьте в состояние компонента активную карточку с предложением (объект с данными предложения или только уникальный идентификатор предложения). Под активной карточкой предложения подразумевается карточка, на которую пользователь навёл курсор. Состояние пригодится нам в дальнейшем для реализации отображения маркеров предложений на карте.»

И не могу придумать, как наиболее изящно фильтровать оферы по городу.

2023-07-12 18:32 UTC, PalantKellad commented on src/components/offer-card/offer-card.tsx
> +		setId(evt.target.id);
Так, тут я вроде бы понял, что это всегда будет пустая строка. И так вроде бы Реакт девтузл и показывает.
Нужно назначать по идее item.id.

2023-07-13 08:44 UTC, PalantKellad commented on src/components/app/app.tsx
> +						//Вот здесь пока затуп. Нужно же передавать в проп нужный элемент списка.
Возможно нужно сделать какой-то общий шаблон, в нём Outlet, и в него уже передавать через useParams id, по которому вызывать нужный элемент списка для рендеринга.
Или я как-то неправильно понимаю Роутер.

2023-07-13 19:11 UTC, baileys-li requested changes
Я позже поревьюрю подробнее

2023-07-13 19:13 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +	}
Смотри карточка активна только одна, значит эта стейт компонента выше, а не конкретной карточки

2023-07-13 19:18 UTC, PalantKellad commented on src/components/offer-card/offer-card.tsx
> +	}
Да, я подозревал, но пока не понял, как стейты прокидывать. Завтра разберусь, спасибо.

2023-07-14 05:40 UTC, PalantKellad commented on src/pages/favorites.tsx
> +	//Получилось что-то такое, но здесь итерация в итерации, и я не могу вставить это в JSX. Я подумал, что может собрать массив из получающихся строк, и потом по нему пройтись при помощи map, но во-пер
На сервере объявления уже отсортированы по городу. Пришла мысль, а может можно их сразу рендерить в список, отбирая те, у которых есть закладки, а обёртки с городами создавать по типу паттерна «синглтон», но потом я понял, что в декларативном Реакте такое вряд ли возможно, если возможно в принципе.

2023-07-14 06:39 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +	}
Просто как пропс. Обсудим

2023-07-18 08:26 UTC, PalantKellad commented
Всё работает, но остаётся немного ругани на типы. Я бы это личный созвон отложил.

2023-07-18 08:26 UTC, merged